### ISSUE TITLE
'w' not setting the width anymore

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#8]
Doing ```myBox.w = 1600``` isn't setting the width to 1600px anymore since the updates (not sure which one broke it).

**Comment by keejelo** [comment]
Ok, I'm going to check it out, I had to rewrite some of the code that handles the position and size, sorry.

**Comment by keejelo** [comment]
Should work now, I forgot to add some code, try the latest update of the file "easydlg.js" in the repo:
https://github.com/keejelo/EasyDialogBox/blob/master/js/easydlg.js

btw. if you want, you can read the whole changelog to get info on changes and what's new, if you have not done so already :)
https://github.com/keejelo/EasyDialogBox/blob/master/changelog.txt

**Comment by ray73864** [comment]
Width works perfectly now, but position not so much, the dialog that was created has a left position of 660px, which put it about 450px too far to the right.

That's with a width of 1600px.

**Comment by keejelo** [comment]
Ok, I'll see what I can do, might have something to do with responsiveness, window width and default centering.. (code for box adjustment maybe..)

Did you set a custom position or just width ?
Did it work before I began all this new updates ?

(I'll look into it when I get off work later today)

**Comment by keejelo** [comment]
Made an update now, try the latest file "easydlg.js" in the repos.
I've been doing some testing now, did different sizes and positions, and seems to work..
(also tried with 1600 and it seemed to work ok)

**Comment by ray73864** [comment]
It's working just fine now.

I thought it was still broken, so fired up Chrome (latest version) and it was working, so checked what the difference was between Microsoft Edge (Chromium build) and Chrome itself, and turns out Edge had chosen to continue using 1.735.16 instead of .18.

Forced Edge to refresh the cache and it's now working perfectly.

**Comment by keejelo** [comment]
Good to hear, yes sometimes it's browser cache that is the problem, it also tricks me from time to time, need to keep spamming that refresh, hehe :)
